### PR TITLE
Fix failing linter tests in Readme.md

### LINKED ISSUE #17: Fix CI status

### PR DESCRIPTION
**Pull request by schenkh**
Fix resolves #17

### CODE REVIEW

**Review by webknjaz — CHANGES_REQUESTED** [review]
Fix the commit message

**Comment by schenkh** [comment]
@webknjaz not sure what's wrong with it. Could you give me a hint?

**Comment by webknjaz** [comment]
Well, from this message I'm not sure what is the effect of this commit when applied to the project.

**Comment by webknjaz** [comment]
You can have 100 commits with this message in Git history. Would it be helpful for someone looking at that list trying to make sense of what was going on there?

**Comment by webknjaz** [comment]
Also, it's not tests but linter errors. They are not specific to Travis, but to the project in general and to the pre-commit hooks in this case. The fact that it makes Travis CI job green is one of the visible effects but does not make any sense in terms of project code base and Git history.
Be specific, but high-level. Now you're too generic.

**Comment by schenkh** [comment]
Thanks, so correct approach generally speaking would be what + why, right?
Based on what we discussed so far this option suits better:

1) Title: "What you have done in the imperative mood" Body: "Explain what and why vs. how"

But this article from #5 https://thoughtbot.com/blog/5-useful-tips-for-a-better-commit-message suggests different approach, I suppose.

2) Title: "Why is this change necessary?" Body: "How does it address the issue?"

**Comment by webknjaz** [comment]
I think that (1) is more appropriate

**Comment by webknjaz** [comment]
Plz also fix the PR title

**Comment by schenkh** [comment]
@webknjaz thanks, updated

**Comment by webknjaz** [comment]
I'd be more precise here

**Comment by schenkh** [comment]
Updated

**Review by webknjaz — APPROVED** [review]

**Pull request merged**
