### PR TITLE
Add initial configuration files 

### PR DESCRIPTION
**Pull request by schenkh**
Add initial configuration files (git ignore and attributes, readme, license) fixes #10

### CODE REVIEW

**Review by webknjaz — CHANGES_REQUESTED** [review]
> Adding

This doesn't conform the commit message recommendations.

> Merge branch 'master' into feature/3-initial-config

Plz don't do this now.

**Comment by schenkh** [comment]
>  Adding
> This doesn't conform the commit message recommendations.

Thanks, should be fixed now
> Merge branch 'master' into feature/3-initial-config
> Plz don't do this now.

Ok, I thought it was needed to proceed

**Comment by webknjaz** [comment]
Still not quite there yet: https://github.com/kpi-web-guild/django-girls-blog-schenkh/pull/11/commits

schenkh-pr11-commits

**Comment by schenkh** [comment]
Right, did not check commits tab. After number of attempts to force reset remote branch I decided to re-create it.. I did not know this automatically closes pr. I have created #13.. Also the reason I did 79a4e82f6bc9ea7e4fcaba310211015b43a89458 is because github gave me merge error that was not visible when I pushed using console..

**Comment by webknjaz** [comment]
Well, this is weird, you've probably pushed some merge commit or similar triggering this behavior on GitHub...

**Comment by webknjaz** [comment]
@schenkh BTW you can record your git sessions with asciinema which would allow you share what exactly did you do.

**Pull request closed without merging**
