### PR TITLE
Add initial configuration files

### LINKED ISSUE #6: Add basic configuration and info files
* [x] `README.md`, stating your project title, styled with Markdown
* [x] `LICENSE` file. Find a template for it in plain text or Markdown format. You may use MIT license for simplicity
* [x] `.gitattributes`. Find some template for your repo on github
* [x] `.gitignore`. Find a typical template for your language (Python, Vim, Linux etc.) @ gitignore.io

You'll need to push a new branch (e.g. `features/3-initial-config`) with atomic commits and [create a PR](https://help.github.com/en/articles/creating-a-pull-request) **referencing this issue**.

### PR DESCRIPTION
**Pull request by schenkh**
Add initial configuration files (new attempt). Resolve #6

### CODE REVIEW

**Comment by webknjaz** [comment]
You still have a merge commit in your branch. Get rid of it :)

**Comment by webknjaz** [comment]
Revert just adds another commit on top. I want you to remove commits, not add them :)

P.S. That revert commit is probably made from a computer whether you forgot to set up git user+email in the config. Or maybe you have broken your current config. Either way, you need to fix that.

**Comment by schenkh** [comment]
How can I do it? Here is my term recording https://asciinema.org/a/j0f9BV2agBBtPb8s6SznIubcm. Probably I am doing something wrong but I cannot get what exactly :\

**Comment by webknjaz** [comment]
`git reset --hard` or checkout to the right commit and push that as a branch...

**Comment by webknjaz** [comment]
You have a typo here:
```console
user.email=victor@schenkh@gmail.com                                                                                                               
                 ^
```

**Comment by webknjaz** [comment]
in your case, you can `git reset --hard 77879aa` and then `git push --force` that

**Comment by webknjaz** [comment]
Oh, and interactive rebase cannot see merge commits where the branch history splits into two branches.

**Comment by webknjaz** [comment]
Oh, and interactive rebase cannot see merge commits where the branch history splits into two branches.

**Comment by webknjaz** [comment]
Meanwhile, do #14 which will help you configure your shell to be more informative.

**Comment by schenkh** [comment]
Thank you for the explanation, it's much more clear now. But I've still got conflict that I used to fix with merge - https://cl.ly/ad6db382d887 What should I do about it? Will work on #14

**Comment by webknjaz** [comment]
Well, you could rebase on top of `master`. We'll try merges another time.

**Comment by webknjaz** [comment]
https://github.com/kpi-web-guild/django-girls-blog-schenkh/pull/13/commits/f5a82243bf8ab56297021fbbede3116ac67f74a9 <-- this commit has a misleading title, which only refers to the part of changes. If you cannot come up with a generic commit message for the whole commit contents, it's a sign that you should probably separate such changes.

Let's ignore this for now, but keep it in mind for the future. You can split commits using interactive rebase btw ;)

**Review by webknjaz — APPROVED** [review]

**Comment by webknjaz** [comment]
You can hit Merge now.

**Pull request merged**
